---
- hosts: localhost
  gather_facts: yes
  
  tasks:
  - name: git hub download
    git:
      repo: "https://github.com/Michaelsliem/azure-Openshift-deploy.git"
      key_file: /var/lib/awx/.ssh/id_rsa
      accept_hostkey: True
      dest: /var/lib/awx/download
      force: yes
      version: master
    
  - name:
    shell:
       sudo az group deployment create --name ocpclutserdeploy --template-file /var/lib/awx/download/azuredeploy.mike.json --parameters /var/lib/awx/download/azuredeploy.paramteres.mike.json --resource-group ResourceGroupName
          
