---
- hosts: localhost
  gather_facts: yes
 
  
  vars:
    num_master: 2
    num_infra: 3
    num_worker: 2
 
  tasks:
  - name: git hub download
    git:
      repo: "https://github.com/Michaelsliem/azure-Openshift-deploy.git"
      key_file: /var/lib/awx/.ssh/id_rsa
      accept_hostkey: True
      dest: /var/lib/awx/download
      force: yes
      version: master
      
  - template:
        src: /var/lib/awx/download/azuredeploy.paramteres.mike.json
        dest: /var/lib/awx/download/azuredeploy.paramteres.mike1.json
    
  - name: Create Openshift Deployment
    shell: |
       cd /var/lib/awx/download
       sudo az group deployment create --name ocpdeployment --template-file azuredeploy.mike.json --parameters azuredeploy.paramteres.mike1.json --resource-group ResourceGroupName
          
