---
- hosts: localhost
  gather_facts: yes
 
  
  vars:
    num_master: 2
    num_infra: 3
    num_worker: 2
 
  tasks:
  - name: git hub download
    git:
      repo: "https://github.com/Michaelsliem/azure-Openshift-deploy.git"
      key_file: /var/lib/awx/.ssh/id_rsa
      accept_hostkey: True
      dest: /var/lib/awx/azure-Openshift-deploy
      force: yes
      version: master
    
  - shell: sudo az group deployment create --name ocptestdeployment --template-file /var/lib/awx/azure-Openshift-deploy/azuredeploy.mike.json --parameters /var/lib/awx/azure-Openshift-deploy/azuredeploy.paramteres.mike.json --resource-group ResourceGroupName
          
