---
- hosts: localhost
  gather_facts: False
 
  tasks:
  - name: git hub download
    git:
      repo: 'https://github.com/Michaelsliem/azure-Openshift-deploy.git'
      dest: /tmp/
    
  - name: Create Openshift Deployment
    shell: |
       cd /tmp/azure-Openshift-deploy/
       az group deployment create --name ocpdeployment --template-file azuredeploy.mike.json --parameters azuredeploy.paramteres.mike.json --resource-group ResourceGroupName
          
