---
- hosts: localhost
  gather_facts: False
  connection: local
  
  tasks:

  - name: Create Openshift Deployment
    azure_rm_deployment:
          deployment_name: openshift-cluster-deployment
          deployment_mode: complete
          resource_group_name: ResourceGroupName
          parameters: azuredeploy.paramteres.mike.json
          template: azuredeploy.mike.json
          wait_for_deployment_completion: no
          
