---
- hosts: localhost
  gather_facts: False
  connection: local
  
  
  vars:
    num_master: 2
    num_infra: 3
    num_worker: 2
 
  tasks:
  - name: git hub download
    shell: |
      cd /tmp/
      git clone https://github.com/Michaelsliem/azure-Openshift-deploy.git
  
  - template:
        src: /tmp/azure-Openshift-deploy/azuredeploy.paramteres.mike.json
        dest: /tmp/azure-Openshift-deploy/azuredeploy.paramteres.mike1.json
    
  - name: Create Openshift Deployment
    shell: |
       cd /tmp/azure-Openshift-deploy/
       sudo az group deployment create --name ocpdeployment --template-file azuredeploy.mike.json --parameters azuredeploy.paramteres.mike1.json --resource-group ResourceGroupName
          
