---
- hosts: localhost
  gather_facts: False
  connection: local
  
  tasks:

  - name: Create Openshift Deployment
    azure_rm_deployment:
          deployment_name: openshift-cluster-deployment
          deployment_mode: complete
          resource_group_name: openshift-cluster-group
          template: openshift.json
          wait_for_deployment_completion: no
          
