---
- hosts: localhost
  gather_facts: False
  connection: local
  
  tasks:
  
  - name: Create storage account
    azure_rm_storageaccount:
          resource_group: ResourceGroupName
          name: mike123
          account_type: Standard_LRS
