---
- hosts: localhost
  gather_facts: False
  connection: local
  
  tasks:
  - name: Create instance of Key Vault
    azure_rm_keyvault:
        resource_group: ResourceGroupName
        vault_name: keyvault1
        enabled_for_deployment: yes
        enabled_for_template_deployment: yes
        
  - name: Create storage account
    azure_rm_storageaccount:
          resource_group: ResourceGroupName
          name: mike123
          account_type: Standard_LRS
