---
- hosts: localhost
  gather_facts: False
  connection: local
  
  tasks:
  - name: Create a VitualMachine
    azure_rm_virtualmachine:
          admin_username: "admin"
          admin_password: "Xvale123"
          resource_group: ResourceGroupName
          name: testVM
          vm_size: Standard_D1
          admin_username: chouseknecht
          ssh_password: yes
          image:
              offer: CentOS
              publisher: OpenLogic
              sku: '7.1'
              version: latest
