---
- hosts: localhost
  gather_facts: False
  connection: local
  
  tasks:
  - name: Create a VitualMachine
    azure_rm_virtualmachine:
          admin_username: "mike1"
          admin_password: "crossvale@123"
          resource_group: ResourceGroupName
          name: testVM
          vm_size: Standard_D1
          ssh_password_enabled: yes
          image:
              offer: CentOS
              publisher: OpenLogic
              sku: '7.1'
              version: latest
